### ISSUE TITLE
相册中的二维码大部分无法识别

### ISSUE THREAD

**Issue by jinmei339** [heiBin/QrCodeScanner#1]
识别相册中的二维码图片，如果该图片是通过手机拍摄保存下来的二维码图片，返回的结果都是null,试了好几个都是这样，麻烦修改下

**Comment by heiBin** [comment]
已经优化本地图片识别了，apk Demo和extraLib目录下的so库也同步更新了。

**Comment by jinmei339** [comment]
试了下，没有改善。。。

   public static String decodeFromFile(String filename, BarcodeFormat barcodeFormat) {
        BitmapFactory.Options options = new BitmapFactory.Options();
        Bitmap scanBitmap;
        options.inJustDecodeBounds = true; // 先获取原大小
        scanBitmap = BitmapFactory.decodeFile(filename, options);
        options.inJustDecodeBounds = false; // 获取新的大小

        int heightSampleSize = (int) (options.outHeight / CameraConfigurationManager.screenHeight);
        int widhtSampleSize = (int) (options.outWidth / CameraConfigurationManager.screenWidth);
        int sampleSize = 1;
        if (heightSampleSize >= 1 || widhtSampleSize >= 1 ){
            sampleSize = heightSampleSize > widhtSampleSize? heightSampleSize:widhtSampleSize;
        }

        options.inSampleSize = sampleSize;
        scanBitmap = BitmapFactory.decodeFile(filename, options);
        return getPixelsByBitmap(scanBitmap, barcodeFormat);
    }
这段代码，拿到的sampleSize为1.

我把它改为下面这段，可以成功解码，你可以帮忙在规范下

 private String decodeImageByUri(Uri uri){
        try {
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        BitmapFactory.decodeStream(getContentResolver().openInputStream(uri), null, options);
        //计算采样率
        int reqWidth =dip2px(this,300);
        int reqHeight = dip2px(this,300);
        int sampleSize = BitmapUtil.calculateInSampleSize(options, reqWidth, reqHeight);
        //加载图片
        options.inSampleSize = sampleSize;
        options.inJustDecodeBounds = false;

            mBitmap = BitmapFactory.decodeStream(getContentResolver().openInputStream(uri), null, options);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return DecodeEntry.decodeFromFile(mBitmap,barcodeFormat);
    }

**Comment by jinmei339** [comment]
还有一点不太明白，为什么需要对图片压缩，就能解析出来结果

**Comment by heiBin** [comment]
问题不在图片压缩，图片压缩只是我加上去预防内存溢出。主要是在ndk层对图片数据进行了旋转处理（识别失败情况下会通过改变旋转角度来重新识别），这和Zxing本身的识别算法有关。

**Comment by jinmei339** [comment]
现在测试的图片，拍摄时候，二维码图片是正的，不是旋转过得，也还是解析不出来。

**Comment by jinmei339** [comment]
解析图片中包含条形码的准确率还是不错的，就是二维码的不太高

**Comment by heiBin** [comment]
恩，问题还是出在图片处理这块。因为同一张图片，利用扫码识别是没问题的，直接本地图片识别可能出现识别不了的情况，这种场景我继续优化，也感谢你的建议。

**Comment by jinmei339** [comment]
好的，期待你的更新。

**Comment by heiBin** [comment]
最近微调了本地图片识别，可以下载apk Demo测试下

**Comment by SuperChrisliu** [comment]
@heiBin `因为同一张图片，利用扫码识别是没问题的，直接本地图片识别可能出现识别不了的情况` 是用的zxing解码的吗？我现在就是在win上通过截图的方式获取二维码然后识别，发现有个二维码zxing识别不了，但是zbar能。扫码和本地图片识别效果为什么会不一样啊，你是如何优化的啊？
