### ISSUE TITLE
手机黑屏，相机没有调起来

### ISSUE THREAD

**Issue by ljxx** [heiBin/QrCodeScanner#2]
手机黑屏，相机没有调起来，文本和扫码的动画

**Comment by heiBin** [comment]
你好，Android6.0以上需要检查相机权限是否开启，项目中还没提供动态权限检测功能，你可以检查下应用对应的相机权限是否已经打开，或者提供下你的手机型号。

**Comment by ljxx** [comment]
权限都提供了，完全信任状态，华为荣耀六，6.0

**Comment by andyfun** [comment]
7.0系统 权限都给了，还是黑屏

**Comment by andyfun** [comment]
//        if ((!Parameters.ANTIBANDING_50HZ.equals(parameters.getAntibanding()))
//                && isSupported(Parameters.ANTIBANDING_50HZ,
//                parameters.getSupportedAntibanding())) {
//            parameters.setAntibanding(Parameters.ANTIBANDING_50HZ);
//        }
       // parameters.setPictureFormat(ImageFormat.NV21);

注释掉这个设置 就可以了
